### ISSUE TITLE
error: SchemaError(io.k8s.api.authorization.v1.SubjectAccessReview)

### ISSUE THREAD

**Issue by galberola** [rnzsgh/eks-workshop-sample-api-service-go#20]
```bash
Running command kubectl apply -f hello-k8s.yml 
error: SchemaError(io.k8s.api.authorization.v1.SubjectAccessReview): invalid object doesn't have additional properties 
```

This error is produced because the version of `kubectl` being installed `v1.10.3` is [farther away than the recommended](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl) (no more than 1 minor).

**Comment by galberola** [comment]
**Update:**
PR #18 tries to address this, but using a static number doesn't seem to be the solution.

A recommended approach would be to use the K8s official installation snippet

```bash
curl -sS -o kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
```

> It would be great if we could get the "latest" version of EKS supported on AWS instead

**Comment by rnzsgh** [comment]
Thanks Gustavo. I merged an updated version of kubectrl. Please let me know if you still see this issue.

**Comment by jingnee** [comment]
I love you. It works for me. Thank you @galberola
